In [2]:
import pandas as pd

In [4]:
trafico = pd.read_csv("Average_Daily_Traffic_Counts.csv")

In [5]:
trafico.head()

,ID,Traffic Volume Count Location Address,Street,Date of Count,Total Passing Vehicle Volume,Vehicle Volume By Each Direction of Traffic,Latitude,Longitude,Location,Boundaries - ZIP Codes,Community Areas,Zip Codes,Census Tracts,Wards,:@computed_region_awaf_s7ux
0,414,5838 West,Lake St,11/14/2006,7100,East Bound: 3600 / West Bound: 3500,41.887904,-87.771064,"(41.887904, -87.771064)",32.0,26.0,22216,672.0,7.0,52.0
1,176,320 East,76th St,03/28/2006,8600,East Bound: 3800 / West Bound: 4800,41.756542,-87.617335,"(41.756542, -87.617335)",61.0,67.0,21546,475.0,32.0,31.0
2,715,835 North,Clark St,09/20/2006,16500,South Bound: 16500/ Oneway South Bound,41.897747,-87.631275,"(41.897747, -87.631275)",54.0,37.0,14926,310.0,11.0,22.0
3,316,125 East,24th St,03/30/2006,700,East Bound: 400 / West Bound: 300,41.849302,-87.622658,"(41.849302, -87.622658)",40.0,34.0,21194,193.0,9.0,48.0
4,1294,2924 East,130th St,08/29/2006,4200,East Bound: 2300 / West Bound: 1900,41.659177,-87.552112,"(41.659177, -87.552112)",26.0,52.0,22250,586.0,47.0,47.0

In [7]:
trafico.shape

(1279, 15)

In [8]:
trafico.dtypes

ID                                               int64
Traffic Volume Count Location  Address          object
Street                                          object
Date of Count                                   object
Total Passing Vehicle Volume                     int64
Vehicle Volume By Each Direction of Traffic     object
Latitude                                       float64
Longitude                                      float64
Location                                        object
Boundaries - ZIP Codes                         float64
Community Areas                                float64
Zip Codes                                        int64
Census Tracts                                  float64
Wards                                          float64
:@computed_region_awaf_s7ux                    float64
dtype: object

In [9]:
trafico.shape

(1279, 15)

In [10]:
trafico.describe()

,ID,Total Passing Vehicle Volume,Latitude,Longitude,Boundaries - ZIP Codes,Community Areas,Zip Codes,Census Tracts,Wards,:@computed_region_awaf_s7ux
count,1279.000000,1279.000000,1279.000000,1279.000000,1266.000000,1266.000000,1279.000000,1265.000000,1266.000000,1266.000000
mean,689.937451,19466.301798,41.849394,-87.670298,32.849921,37.849921,18520.457389,369.827668,26.774092,28.432859
std,395.568121,12448.378467,0.083917,0.060891,17.471999,19.441805,5738.749841,237.662993,14.595722,14.794743
min,1.000000,700.000000,41.651861,-87.854842,1.000000,1.000000,2733.000000,1.000000,1.000000,1.000000
25%,348.500000,11350.000000,41.780249,-87.710013,19.000000,25.000000,14920.000000,134.000000,13.000000,16.000000
50%,684.000000,17300.000000,41.871380,-87.662850,34.000000,36.000000,21546.000000,368.000000,28.000000,28.000000
75%,1028.500000,24200.000000,41.909196,-87.628631,46.000000,55.000000,22216.000000,578.000000,39.000000,41.000000
max,1382.000000,165200.000000,42.017888,-87.529702,61.000000,77.000000,26633.000000,800.000000,50.000000,53.000000

In [11]:
trafico.count()

ID                                             1279
Traffic Volume Count Location  Address         1279
Street                                         1279
Date of Count                                  1279
Total Passing Vehicle Volume                   1279
Vehicle Volume By Each Direction of Traffic    1279
Latitude                                       1279
Longitude                                      1279
Location                                       1279
Boundaries - ZIP Codes                         1266
Community Areas                                1266
Zip Codes                                      1279
Census Tracts                                  1265
Wards                                          1266
:@computed_region_awaf_s7ux                    1266
dtype: int64

In [26]:
trafico[trafico.duplicated()].shape

(0, 15)

In [27]:
trafico.tail()

,ID,Traffic Volume Count Location Address,Street,Date of Count,Total Passing Vehicle Volume,Vehicle Volume By Each Direction of Traffic,Latitude,Longitude,Location,Boundaries - ZIP Codes,Community Areas,Zip Codes,Census Tracts,Wards,:@computed_region_awaf_s7ux
1274,1154,806 North,State St,09/21/2006,21100,North Bound: 9900 / South Bound: 11200,41.896924,-87.628206,"(41.896924, -87.628206)",54.0,37.0,21182,230.0,11.0,22.0
1275,396,13200 South,Torrence Ave,11/08/2006,15100,North Bound: 7400 / South Bound: 7700,41.655545,-87.559298,"(41.655545, -87.559298)",26.0,52.0,22250,586.0,47.0,47.0
1276,762,3121 South,Pulaski Rd,09/14/2006,29500,North Bound: 15400 / South Bound: 14100,41.836244,-87.724337,"(41.836244, -87.724337)",57.0,32.0,21569,200.0,28.0,14.0
1277,257,256 East,35th St,03/29/2006,10200,East Bound: 4800 / West Bound: 5400,41.831081,-87.619334,"(41.831081, -87.619334)",36.0,1.0,4301,222.0,9.0,48.0
1278,950,2032 North,Pulaski Rd,10/05/2006,21300,North Bound: 10800 / South Bound: 10500,41.918169,-87.726590,"(41.918169, -87.72659)",1.0,21.0,22535,76.0,49.0,27.0

In [32]:
trafico.ID.value_counts()

AttributeError: 'DataFrame' object has no attribute 'ID'

In [31]:
trafico([ID])

NameError: name 'ID' is not defined